function plotLeaderAndAgentTrajectory3D(TrajectoryDefVelocity, AgentSetup, Framework, EdgesFormation)
    figure(1);

    % Plot the leader's desired trajectory in 3D (red dashed line)
    plot3( ...
        TrajectoryDefVelocity.PosLeaderDesired(1, :)', ...
        TrajectoryDefVelocity.PosLeaderDesired(2, :)', ...
        TrajectoryDefVelocity.PosLeaderDesired(3, :)', ...
        'LineStyle', '-.', 'Color', 'red', 'LineWidth', 2 ...
    );
    hold on;

    % Plot the actual trajectory of agent 3 in 3D (blue solid line)
    plot3( ...
        AgentSetup.positionsArray_M(3 * Framework.SPACE_DIM - 2, :), ...
        AgentSetup.positionsArray_M(3 * Framework.SPACE_DIM - 1, :), ...
        AgentSetup.positionsArray_M(3 * Framework.SPACE_DIM, :), ...
        'LineStyle', '-', 'Color', 'blue', 'LineWidth', 2 ...
    );
    hold on;

    % Overlay the final formation framework (edges between agents)
    [grf, points] = Framework3Dplot(AgentSetup.positionsArray_M(:, end), EdgesFormation.E_ARRAY);
end